### ISSUE TITLE
How come this green button is not shown when it's 780px wide as tablet?

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [AnnieTaylorCHEN/Fotomatic#1]
https://github.com/AnnieTaylorCHEN/Fotomatic/blob/9f74ab98cb0ab681a4bb5a007bb1e781b575caff/resources/css/style.css#L81

I thought the "Join Us" green could be shown on the right side? Why not show up here? Is there anything I can do to make it show up?

**Comment by kgar** [comment]
The "Join Us" button only lives in the mobile header, and the mobile header only appears when the screen is 450px or less.

![image](https://user-images.githubusercontent.com/4632129/45626239-a3a02200-ba54-11e8-9243-7528972c8564.png)

**Comment by kgar** [comment]
To make it show in the Desktop header, copy it into that \<ul\>.

**Comment by AnnieTaylorCHEN** [comment]
Great it works now! I realize in this case I need the button twice, one hidden in desktop, shown in tablet with desktop menu, another together with mobile menu.
