### ISSUE TITLE
Why do I have to set a fixed width here?

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [AnnieTaylorCHEN/Fotomatic#2]
https://github.com/AnnieTaylorCHEN/Fotomatic/blob/9f74ab98cb0ab681a4bb5a007bb1e781b575caff/resources/css/style.css#L223

I tried width: auto but it seems it always sticking out little. I tried many ways and in the end only width 320px (tested 320px as smallest cell phone screen on Chromium dev tool) works perfect with all the size. But why wouldn't the width: auto work? I thought it shrinks everything within its parents?

**Comment by kgar** [comment]
Here's an explanation of auto width: The initial width of a block level element like div or p is auto. This makes it expand to occupy **all available horizontal space within its containing block**. If it has any horizontal padding or border, the widths of those do not add to the total width of the element.

I've bolded the part that is relevant to this situation. Because the parent container does not have a specified width, the child content can take up all of the space it needs to prevent a line break in the text "Email us to request a demo and be in our waiting list for the Febuary 2017 release!". In specifying a width, whether a calculated REM / EM -based width or an explicit width, you're keeping the child content from determining the width.

**Comment by kgar** [comment]
I had to look up auto-width again, so I was looking at this SO article: https://stackoverflow.com/questions/17468733/difference-between-width-auto-and-width-100-percent

**Comment by AnnieTaylorCHEN** [comment]
I see.... so even that text (under class="email") is set as display: none in responsive mode, it can still affect the whole part? Because it's the sibling of "header"?

**Comment by kgar** [comment]
Oh, no, "display: none" does not take up any space. 

Alternatively, "visibility: hidden" will make the content invisible, but it will still take up space.

**Comment by kgar** [comment]
Something else may be going on...

**Comment by kgar** [comment]
Looking at it again, I see that the ruleset for #sign-up-cta has this:
"margin-left: 100px;".

This style, when the screen is very small, causes this visual issue:

![image](https://user-images.githubusercontent.com/4632129/45650695-b9cdd280-ba94-11e8-924d-44a8689041a3.png)

Here's when I scroll to the right:

![image](https://user-images.githubusercontent.com/4632129/45650724-da962800-ba94-11e8-9e7c-5f9379cd51a3.png)

**Comment by AnnieTaylorCHEN** [comment]
Ahhhhh I see. That looks very much like the "sticking out" thing. Do you think the way I did is the best thing to do in this situation, or is there any better way? Those tiny things are always tricky.

**Comment by kgar** [comment]
This is probably not the _best_ fix, but in the 780px #sign-up-cta ruleset, you could do:
margin-left: 0;
padding-right: 0;

I believe the horizontal padding and margins were leftover from the larger view.

**Comment by kgar** [comment]
To make sense of what I'm seeing, open devtools, go to the Elements tab, and select

![image](https://user-images.githubusercontent.com/4632129/45651049-e3d3c480-ba95-11e8-8f02-cc98698ad4c4.png)

I saw that the margin was pushing from the left, and the padding was pushing from the right.

**Comment by AnnieTaylorCHEN** [comment]
Hmmm... I did this in dev tool. I added the extra rule as you said, then try uncheck 320px. It seems this Instant Format Camera works fine, however the "Join Us" green button got eaten half on the right side. 
![screenshot from 2018-09-18 19-28-31](https://user-images.githubusercontent.com/25988475/45705179-30dc9700-bb79-11e8-9822-0933aaf1da0e.png)

Does this happen at your end too?

**Comment by kgar** [comment]
Here's what I'm seeing at the moment:
![image](https://user-images.githubusercontent.com/4632129/45706659-6e71fd80-bb42-11e8-8c7a-7f2afe78c7ee.png)

**Comment by kgar** [comment]
Here's with iPhone 5/SE:
![image](https://user-images.githubusercontent.com/4632129/45706743-aa0cc780-bb42-11e8-8482-614737dc8d72.png)

**Comment by AnnieTaylorCHEN** [comment]
Did you change the code with dev tool and it showed up fine? Hmmm, I tried locally, then use the dev tool. It didn't work... anyways, let's leave it here as 320px seems to work fine for all sizes.
